# Generated by Django 2.0.12 on 2020-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('emailID', models.EmailField(max_length=254)),
            ],
        ),
    ]
