# Generated by Django 2.0.12 on 2020-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='password',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
