# Generated by Django 2.0.12 on 2020-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_search_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='emailID',
            field=models.EmailField(default='abc@abc.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='search',
            name='phoneNumber',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='userName',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
