# Generated by Django 2.0.12 on 2020-05-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200508_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search',
            new_name='searchUser',
        ),
    ]
