# Generated by Django 2.0.12 on 2020-05-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200508_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchuser',
            name='phoneNumber',
            field=models.FileField(upload_to=''),
        ),
    ]
