# Generated by Django 2.0.12 on 2020-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200512_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchuser',
            name='label',
            field=models.CharField(default='label', max_length=200),
            preserve_default=False,
        ),
    ]
