# Generated by Django 2.0.12 on 2020-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_searchuser_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchuser',
            name='UserName',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchuser',
            name='FileName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='searchuser',
            name='UploadCSV',
            field=models.FileField(upload_to='media/'),
        ),
    ]
