# Generated by Django 2.0.12 on 2020-05-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200518_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchuser',
            name='UserName',
        ),
    ]
