# Generated by Django 2.0.12 on 2020-05-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_searchuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchuser',
            name='UserName',
        ),
    ]
