# Generated by Django 2.0.12 on 2020-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_searchuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='emailID',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='model',
            field=models.CharField(choices=[('Naive Bayes', 'Naive Bayes'), ('Decision Tree', 'Decision Tree'), ('Support Vector Machine', 'Suport Vector Machine'), ('KNN', 'KNN'), ('Random Forest', 'Random Forest')], default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
