# Generated by Django 2.0.12 on 2020-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_modelresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='userName',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
