# Generated by Django 2.0.12 on 2020-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_modelresult_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='userName',
            field=models.CharField(default='Akshobhya', max_length=200),
        ),
    ]
